version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_PORT=5432
      - POSTGRES_PASSWORD=1301
      - POSTGRES_USER=postgres
      - POSTGRES_DB=medhub
      - POSTGRES_HOST=db
      - POSTGRES_HOSTNAME=localhost
    depends_on:
      - db
    networks:
      - medhub-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1301
      - POSTGRES_USER=postgres
      - POSTGRES_DB=medhub
    ports:
      - "5432:5432"
    networks:
      - medhub-network

volumes:
  postgres_data:


networks:
  medhub-network:
    driver: bridge
