version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: medical_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: medical_db
      LC_ALL: C.UTF-8
    networks:
      - medical_network
    ports:
      - "5432:5432"
    healthcheck:  # Health check para garantir que o PostgreSQL está pronto
      test: ["CMD-SHELL", "pg_isready -U postgres -d medical_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: medical_app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    networks:
      - medical_network
    ports:
      - "8000:8000"
    depends_on:  # Define a dependência com base no health check
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:12345678@db:5432/medical_db

networks:
  medical_network:
    driver: bridge